from typing import Optional, Protocol
from app.domain.news_orm import NewsEntity

class NewsRepositoryInterface(Protocol):
    def save(self, news: NewsEntity) -> bool | None: ...
    def save_ignore_duplicate(self, news: NewsEntity) -> bool | None: ...
    def read_by_type(self, type: str) -> NewsEntity | None: ...