from typing import Optional, Protocol
from app.news.domain.news_entity import NewsEntity

class NewsRepositoryInterface(Protocol):
    def save(self, news: NewsEntity) -> bool: ...
    def save_ignore_duplicate(self, news: NewsEntity) -> bool: ...
    def read_economy_score_priority(self, ) -> list[NewsEntity]: ...
    def read_world_score_priority(self, ) -> list[NewsEntity]: ...
    def read_total_score_priority(self, ) -> list[NewsEntity]: ...