from typing import Optional, Protocol
from app.news.domain.news_entity import NewsEntity

class NewsRepositoryInterface(Protocol):
    def save(self, news: NewsEntity) -> bool: ...
    def save_ignore_duplicate(self, news: NewsEntity) -> bool: ...
    def read_by_type(self, type: str) -> NewsEntity | None: ...