from typing import Optional, Protocol
from app.modules.news.infra.model.news_orm import NewsEntity

class NewsRepositoryInterface(Protocol):
    def save(self, news: NewsEntity) -> bool | None: ...
    def read_by_type(self, type: str) -> NewsEntity | None: ...