from typing import Optional, Protocol
from app.modules.news.domain.entities.news import NewsEntity

class NewsInterfaceRepository(Protocol):
    def save(self, news: NewsEntity) -> bool | None: ...
    def get_news(self) -> NewsEntity | None: ...
    def get_by_type(self, type: str) -> NewsEntity | None: ...